### ISSUE TITLE
What's the benefit for aiohttp-wsgi + django?

### ISSUE THREAD

**Issue by gera2ld** [etianen/aiohttp-wsgi#11]
It seems that `aiohttp-wsgi` just runs an application in an executor, which by default [is just a thread pool](https://docs.python.org/3/library/asyncio-eventloop.html#executor), with a default pool size of 5 threads.

So if the application is designed with blocking APIs, such as flask and django, it will actually be executed via multi-threading and could not take advantage of co-routines. Then what's the benefit for using `aiohttp-wsgi`?

**Comment by etianen** [comment]
An excellent question!

If you're only going to use Django, then there's no real advantage over
using any other wsgi server. A few minor advantages include:

- Pretty decent async static file server via aiohttp
- Ability to schedule background tasks as coroutines from the Django app
using loop.create_task()

However, the main reason this library exists is that it allows you you run
Django alongside an aiohttp application, allowing you to implement critical
pieces of your app as async, but keep most of it inside Django.

**Comment by gera2ld** [comment]
That makes sense. Thanks a lot!
