### ISSUE TITLE
Serving WSGI app from Python code

### ISSUE THREAD

**Issue by NicolasLM** [etianen/aiohttp-wsgi#20]
`aiohttp-wsgi` has a way to serve WSGI apps from the CLI, but there is no easy way to do it from Python code. By easy I mean with a single function call.

The `serve` function in `__main__` is almost good for this use case, except that it expects args from the CLI.

For inspiration, I really like how waitress does it with [`waitress.serve`](https://docs.pylonsproject.org/projects/waitress/en/latest/#usage).

**Comment by etianen** [comment]
It's a nice idea. I suspect that it can be done very easily by adapting the
functions in __main__. I don't have time to do it myself right now, but I
would review a pull request that added a public aiohttp_wsgi.serve()
method, with accompanying documentation.

**Comment by etianen** [comment]
Added in 0.8.

https://aiohttp-wsgi.readthedocs.io/en/stable/wsgi.html#aiohttp_wsgi.serve

**Comment by NicolasLM** [comment]
This is awesome, thank you!

**Comment by etianen** [comment]
You might have noticed that a lot of the public API for aiohttp-wsgi takes it's inspiration from waitress already. The new `serve` function, along with the existing CLI, are pretty much drop-in replacements.

I'm not 100% convinced there's any reason to use aiohttp-wsgi over waitress if there's no intention to use any async features. I'd be curious to see a performance comparison of the two servers for a hello world WSGI app. I have no idea which one would be faster!

**Comment by NicolasLM** [comment]
For me the reason is quite simple: waitress uses Python `asyncore` which is deprecated and may be removed completely from Python at some point. It also has seen little to no development lately.

By using asyncio you're basically using the blessed asynchronous framework for Python which is a good thing.

I did a small benchmark with `wrk` and waitress is slightly faster but there is some room for improvement. For instance disabling the `aiohttp` access log raises a 15% speedup.

**Comment by keis** [comment]
Cool stuff. We've been using some copy-pasted and glued together bits of the __main__ up until now. Motivation can pretty much be summed up in that we want to run other asyncio tasks in the same process without adding another async concept like threads to the picture
