### ISSUE TITLE
Update to aiohttp 3+

### ISSUE THREAD

**Issue by nite** [etianen/aiohttp-wsgi#22]
Is there any specific reason aiohttp-wsgi is pinned to `aiohttp<3` (in setup.py) @etianen ?

**Comment by etianen** [comment]
So that, if aiohttp does a major version upgrade (which implies breaking
changes), it won't break!

I shall push out a version that uses aiohttp 3 in the next day or so.

**Comment by etianen** [comment]
Fixed in 0.8.
