### ISSUE TITLE
Version of Python

### ISSUE THREAD

**Issue by cinvoke** [etianen/aiohttp-wsgi#3]
I do not see any dependency information.  Is python3.4 a requisite for this because aiohttp requires it?  And if so, can I use this with an app that was written in python2.7?

**Comment by etianen** [comment]
I'm afraid that it requires Python 3.3 or greater.

Dependencies are listed in the setup.py file:
https://github.com/etianen/aiohttp-wsgi/blob/master/setup.py#L29
