### ISSUE TITLE
Please provide support for aiohttp 0.22

### ISSUE THREAD

**Issue by garyvdm** [etianen/aiohttp-wsgi#8]
I would like to use the new testing functionality in aiohttp 0.22. But the setup.py for aiohttp-wsgi disallows it. 

I ran the aiohttp-wsgi tests against aiohttp 0.22.2 and all tests passed. My application also runs correctly with aiohttp-wsgi and aiohttp 0.22.2. 

What is the reason for not allowing aiohttp 0.22 in your setup.py. If you let me know, I will happily work on these issues.

**Comment by etianen** [comment]
The reason is simply that aiohttp has a habit of introducing breaking changes on minor version bumps. This has broken aiohttp-wsgi before.

I've just checked, and it looks like 0.22.2 runs just fine. I've just released aiohttp-wsgi 0.6.1 with the updated dependency.

**Comment by garyvdm** [comment]
Thank you!
