### ISSUE TITLE
Running under multiple processes?

### ISSUE THREAD

**Issue by mackeyja92** [etianen/aiohttp-wsgi#9]
Is it possible to run this under multiple processes using a `ProcessPoolExecutor` to allow scaling past a single process? I have tried to replace the default executor with the `ProcessPoolExecutor` but get some pickling errors. 

If not, is there a way to expose the whole app to apache/nginx/gunicorn?

[This](https://stackoverflow.com/questions/36676519/using-web-application-with-multiprocessing "Stackoverflow using web application with multiprocessing") looks interesting but I have no idea how to implement it into a project.

**Comment by mackeyja92** [comment]
After reading more of aiohttp's docs I see I can run it under gunicorn. ❤️

**Comment by etianen** [comment]
Running it under gunicorn will run multiple aiohttp instances, each of
which will have a thread pool for aiohttp-wsgi. Which is probably a  nice
way to utilise multi-code.

Running under a ProcessPoolExecutor would be relatively easy to accomplish,
but would involve removing some of the aiohttp and asyncio keys that were
added to the wsgi environ if a process pool executor is detected.

**Comment by mackeyja92** [comment]
Yes, using gunicorn was the easiest way to go. With -w4 I get 4 loops running individually of each other and it is working great.
